echo "🚀 Instagram Clone - Render Deployment"
echo "======================================"

echo ""
echo "📋 Pre-Deployment Checklist:"
echo "✅ Package.json updated with 'node index.js' start script"
echo "✅ CORS configuration updated for production"
echo "✅ Socket.io ports unified for Render"
echo "✅ Frontend API URLs configured with environment variables"
echo "✅ MongoDB connection ready"

echo ""
echo "📊 Your Project Status:"
echo "Backend: Express.js + Socket.io + MongoDB"
echo "Frontend: Next.js + TypeScript + Tailwind"
echo "AI: Google Gemini API integration"
echo "Database: MongoDB Atlas (ready)"

echo ""
echo "🎯 Next Steps:"
echo ""
echo "1. 📤 PUSH TO GITHUB:"
echo "   git add ."
echo "   git commit -m 'Ready for Render deployment'"
echo "   git push origin main"
echo ""
echo "2. 🖥️ DEPLOY BACKEND (Web Service):"
echo "   - Go to https://dashboard.render.com"
echo "   - New → Web Service"
echo "   - Connect GitHub repo"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Add all environment variables from .env"
echo ""
echo "3. 🌐 DEPLOY FRONTEND (Static Site):"
echo "   - New → Static Site"
echo "   - Same GitHub repo"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: frontend/.next"
echo "   - Environment: NEXT_PUBLIC_API_URL=https://your-backend.onrender.com"
echo ""
echo "4. 🔄 UPDATE GOOGLE OAUTH:"
echo "   - Add callback URL: https://your-backend.onrender.com/users/auth/google/callback"
echo ""
echo "💰 Cost: FREE (750 hours/month)"
echo "🕒 Deploy Time: ~10 minutes"
echo ""
echo "📖 Full Guide: See RENDER-DEPLOY.md"
echo ""
echo "🎉 Your Instagram clone will be live on the internet!"